/**
 * Created by rkhabibullin on 18.10.2017.
 */


export interface ProjectEvent{
    type: string;
    value: any;
    projectId: number;
}

export let projectActions = {
  LOAD_LIST: "PROJECTS LOAD_ALL",
  LIST_LOADED: "PROJECTS LIST_LOADED",
  CREATE: "PROJECTS CREATE",
  ADDED: "PROJECTS ADDED",
  LOAD_FAILED: "PROJECTS LOAD FAILED",
  CREATE_FAILED: "PROJECTS CREATE FAILED",
  LOAD_PARAMS: "PROJECTS LOAD PARAMS",
  LOAD_INSTANCES: "PROJECTS LOAD INSTANCES",
  INSTANCES_LOADED: "PROJECTS INSTANCES LOADED",
  LOAD_BUILDS: "PROJECTS LOAD BUILDS",
  BUILDS_LOADED: "PROJECTS BUILDS LOADED",
  LOAD_QA_BUILDS: "PROJECTS LOAD QA BUILDS",
  QA_BUILDS_LOADED: "PROJECTS QA BUILDS LOADED",
  SAVE_PARAMS: "PROJECTS SAVE PARAMS",
  PARAMS_SAVED: "PROJECTS PARAMS SAVED",
  PARAMS_LOADED: "PROJECTS PARAMS LOADED"
};